// <auto-generated />
using System;
using Challenge_Clyvo_Vet_DotNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Challenge_Clyvo_Vet_DotNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524060520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Challenge_Clyvo_Vet_DotNet.Models.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPet"));

                    b.Property<DateTime>("DataNascimentoPet")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO_PET");

                    b.Property<string>("EspeciePet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ESPECIE_PET");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    b.Property<string>("NomePet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_PET");

                    b.Property<string>("RacaPet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RACA_PET");

                    b.Property<string>("StatusCastrado")
                        .HasMaxLength(1)
                        .HasColumnType("NCHAR(1)")
                        .HasColumnName("STATUS_CASTRADO")
                        .IsFixedLength();

                    b.HasKey("IdPet");

                    b.ToTable("T_CLV_PET", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
